name: Push commit
on:
  push:
    branches:
      - 'master'

jobs:
  report:
     runs-on: ubuntu-20.04
     steps:
     - name: SSH Remote Commands
       uses: appleboy/ssh-action@v0.1.2
       with:
           host: ${{ secrets.HOST }} #public IP
           username: ${{ secrets.USERNAME }}
           password: ${{ secrets.PRIVATE_KEY }}
           port: 22
     - name: Run script file
       uses: actions/checkout@v2
       run: | 
         cd /home/ubuntu/
         /home/ubuntu/test.sh
       
         
