name: Push commit
on:
  push:
    branches:
      - 'master'

jobs:
  build:
     runs-on: ubuntu-20.04
     steps:
     - name: SSH Remote Commands
       uses: appleboy/ssh-action@master
       with:
           host: ${{ secrets.HOST }} #public IP
           username: ${{ secrets.USERNAME }}
           key: ${{ secrets.PRIVATE_KEY }}
     - name: remote-bash
  # You may pin to the exact commit or the version.
  # uses: shinhwagk/remote-bash@c03b11eac4cceccef56a495916311d9d49875f4d
       run: | 
          cd /home/ubuntu/
          /home/ubuntu/test.sh
       shell: bash
       
         
